version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ivzakaz-bot
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    env_file:
      - .env